Fix/fm 13 leftsearchable
FirelyTeam/Fhir.Metrics pull request #14
Opened 2020-06-10 09:49 UTC by alexzautke

Fixes #13

2020-06-10 12:28 UTC, alexzautke commented
Fix breaks for:
q1 = system.Quantity("9.6g");
q2 = system.Quantity("0.94e1g");

Different solution needed

2020-08-03 12:09 UTC, cknaap requested changes

2020-08-03 12:09 UTC, cknaap commented on src/Fhir.Metrics/Utils/SearchExtensions.cs
> +            return $"E{exponent}x{leftSearchable}";
What if exponent >9 (that is: longer than 1 digit)?
Suggest to simply output 2 digits and error on exponent > 99.

2020-08-13 14:43 UTC, abelenthoven approved these changes

2020-08-13 14:44 UTC, merged