Add support for annotations in a metric
FirelyTeam/Fhir.Metrics pull request #9
Opened 2019-03-24 21:21 UTC by alexzautke

Accept the following metrics as valid:
"/{count}"
"{rbc}"
"ml.{count}"
"mL/min/{1.73_m2}"

2019-03-25 14:00 UTC, cknaap requested changes

2019-03-25 14:00 UTC, cknaap commented on src/Fhir.Metrics/Utils/Parser.cs
> +        public static Regex Annontations = new Regex(@"{[^{}]*}", RegexOptions.Compiled);
typo

2019-03-25 14:00 UTC, cknaap commented on src/Fhir.Metrics/Utils/Parser.cs
> +                else // e.g. // Annotation is directly combined with another unit
I would add a comment with an example of each case for the next developer.

2019-03-25 14:00 UTC, cknaap commented on src/Fhir.Metrics/Model/Metrics.cs
> +            if (symbol.Equals(Unity))
Maybe cleaner to add Unity / 1 to Units?

2019-03-25 14:00 UTC, cknaap commented on test/Fhir.Metrics.Tests/Tests/TestMetrics.cs
> +            Metric metric;
Would be nice to have unittests that show how the expression is being rewritten, also for documentation.
Could you add extra Asserts for that?

2019-03-25 16:19 UTC, alexzautke commented on src/Fhir.Metrics/Model/Metrics.cs
> +            if (symbol.Equals(Unity))
I struggled with the same question. Prefer to keep it this way as Metrics.cs is the best place for it. For me it doesn't make sense to still add it in this class as we can return the unit here directly.

2019-03-26 07:43 UTC, cknaap approved these changes

2019-03-26 07:53 UTC, merged

2019-03-26 10:01 UTC, mharthoorn commented on src/Fhir.Metrics/Utils/Parser.cs
> +        private static string CanonicalizeAnnotations(string expression)
This function transforms the source expression to prepare it for parsing. Eventually, it's beneficial to have the parser itself handle this. Especially since it has a significant impact on performance with high volumes.

2019-03-26 10:01 UTC, mharthoorn commented on src/Fhir.Metrics/Utils/Parser.cs
> +                else if (expression[match.Index - 1].Equals('/') || expression[match.Index - 1].Equals('.')) // Annotation is part of a multiplication or division, e.g. "/{count}" or "10*3.{RBC}"
Have a function .IsMultiplyOrDivisionOperator(string) clears up the code and removes the need for comments..

2019-03-26 10:01 UTC, mharthoorn commented on src/Fhir.Metrics/Model/Metrics.cs
> +                return new Unit("Unity", Unity, "");
Do not create a new instance for unit, but create a static and return that.

2019-03-26 10:01 UTC, mharthoorn commented on src/Fhir.Metrics/Utils/Parser.cs
> +            var annotations = new Regex(@"{[^{}]*}", RegexOptions.Compiled);
It looks like you can use static Regex Annotations here.

2019-03-26 10:01 UTC, mharthoorn commented on src/Fhir.Metrics/Utils/Parser.cs
> +            return TokenPattern.Match(expression).Captures("m").ToList();
This code was already inefficient in that it did an IsMatch and then a Match. Both Annotations and TokenPattern benefit from a refactor to:
``` csharp
  var match = TokenPattern.Match(expression);
  if (match.Success) ...
```

2019-03-28 12:01 UTC, alexzautke commented on src/Fhir.Metrics/Utils/Parser.cs
> +        private static string CanonicalizeAnnotations(string expression)
Agreed, but delayed for a proper solution for a parser not build on top of Regex